services:
  web:
    build: .
   # ports:
    #  - "4500:8000"
    expose:
      - "8000"
    restart: always
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb
    depends_on:
      - db 
  nginx:
    image: nginx:alpine
    container_name: bitedash_nginx
    ports:
      - "4500:80"  # Bahar se koi port 4500 par aayega, Nginx use pakad lega
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - web 
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_sec
    ports:
      - "5000:3000"
    volumes:
      - grafanadata:/var/lib/grafana
    restart: always


volumes:
  pgdata:
  mysqldata:
  mongodata:
  grafanadata:

